[package]
name = "dsc_lib"
version = "3.0.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.26"
clap = { version = "4.5.17", features = ["derive"] }
derive_builder ="0.20.1"
indicatif = "0.17.0"
jsonschema = "0.22.3"
linked-hash-map = "0.5.6"
num-traits = "0.2.14"
regex = "1.7.0"
reqwest = { version = "0.12.8", features = ["rustls-tls"], default-features = false }
schemars = { version = "0.8.12", features = ["preserve_order"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
serde_yaml = { version = "0.9.3" }
thiserror = "1.0.0"
security_context_lib = { path = "../security_context_lib" }
semver = "1.0.0"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.37"
tracing-indicatif = { version = "0.3.6" }
tree-sitter = "0.24.3"
tree-sitter-dscexpression = { path = "../tree-sitter-dscexpression" }

[dev-dependencies]
serde_yaml = "0.9.3"

[build-dependencies]
cc="1.1.20"
